# Generated by Django 4.0.4 on 2022-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dropdownapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='citiesid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='countriesid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='statesid',
            field=models.IntegerField(),
        ),
    ]
